version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:///./couple_compass.db
      REDIS_URL: redis://redis:6379
      ENVIRONMENT: development
    depends_on:
      - redis
    restart: always
    networks:
      - app-network
    volumes:
      - ./backend/couple_compass.db:/app/couple_compass.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api/v1
      NEXT_PUBLIC_BFF_URL: http://localhost:4000/graphql
      NEXT_PUBLIC_WS_URL: ws://localhost:8000/ws
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-nextauth-secret
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
